### PR TITLE
PR with JNA support

### PR DESCRIPTION
**Pull request by soywiz**
As requested here: https://github.com/jhult/dokany-java/issues/1#issuecomment-325205677

### CODE REVIEW

**Comment by Liryna** [comment]
Hi @soywiz ,

If you are willing to maintain the java wrapper, I can give you directly access to the repository for you to include you change.
This would be really awesome ❤️ and extremely appreciate !

**Comment by soywiz** [comment]
Ok. Give me access if you wish :) But I cannot promise investing too much time on this since I have other projects

**Comment by Rondom** [comment]
> Ok. Give me access if you wish :) But I cannot promise investing too much time on this since I have other projects

Everything is better than having an outdated version here.

**Comment by Liryna** [comment]
Invitation launched 👍 @soywiz 
@jhult if you also would like to join the team, do not hesitate !

**Comment by jhult** [comment]
@Liryna, I am interested in joining the team.

**Comment by Liryna** [comment]
Welcome to the team @jhult 😎

**Pull request merged**
