### PR TITLE
WIP JNA Dokan

### PR DESCRIPTION
**Pull request by soywiz**
PR for Issue #6 Use JNA?

This is a WIP and it is not finished yet, but you can start reviewing it.

### CODE REVIEW

**Comment by Liryna** [comment]
Hi @soywiz ,

This seems to look really alright for now ❤️ I didn't test it but the logic seems to be good !
Tell me when you feel it is ready and I can test it 😃 (not a Java dev so a little README update at the end to explain how to use it would be the best !)

**Comment by soywiz** [comment]
Hey. Sorry for the huge delay :(
I was not able to continue at that moment, and later I forgot about this.
Even when this PR includes some work, I had some issues that are still unresolved. That's why I didn't suggest to merge it yet.
I don't know whether I will have time this weekend to finish this,  but it will try.

**Comment by soywiz** [comment]
@ihsanhaikalz @Liryna I have tried to fix it. And even when I have fixed a couple of issues, I can't get it working properly. It would require more time or someone that knows Dokan better; and I'm pretty busy lately. JNA Definitions seems to work fine, but return codes are a bit complex. I cannot invest more time on this, at least at the moment.
So please feel free to do whatever you want: close this PR without merging, merge it and fix it later or whatever.
Sorry for not being able to complete it :(
Regards

**Comment by Liryna** [comment]
😢 alright
I let it open in case someone would like to look into it !

**Comment by Liryna** [comment]
hi @jhult and @soywiz ,

Seems like lots of work has been done here !
What is the status of the implementation ? ❤️

**Comment by Rondom** [comment]
Hasn't there also been some implementation based on JNR? I cannot find it. So probably my memor yis blurry and I mistook that PR you are talking about as an implementation based on JNR.

(I have never done any Java interacting with native code so I don't even know about the differences JNA, JNI and JNR and thus do not know about what is the latest and greatest)?

**Pull request closed without merging**
